name: pick-place-gpu-environment
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pytorch
  - pytorch-cuda
  - torchvision
  - torchaudio
  - numpy
  - opencv
  - matplotlib
  - pyyaml
  - pip:
      - ultralytics==8.0.166